### ISSUE TITLE
 RuntimeError: [enforce fail at inline_container.cc:222] . file not found: archive/data/94577727233808

### ISSUE THREAD

**Issue by vnben** [Henry1iu/TNT-Trajectory-Predition#20]
Traceback (most recent call last):
  File "train_tnt.py", line 129, in <module>
    train(args.local_rank, args)
  File "train_tnt.py", line 21, in train
    train_set = ArgoverseInMemv2(pjoin(args.data_root, "train_intermediate")).shuffle()
  File "/root/autodl-tmp/TNT-Trajectory-Predition-main/core/dataloader/argoverse_loader_v2.py", line 62, in __init__
    self.data, self.slices = torch.load(self.processed_paths[0])
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 592, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 851, in _load
    result = unpickler.load()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 843, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 831, in load_tensor
    storage = zip_file.get_storage_from_record(name, size, dtype).storage()
RuntimeError: [enforce fail at inline_container.cc:222] . file not found: archive/data/94577727233808

could u tell me how to solve this question. QAQ
I really have no idea.
我的CUDA版本是11.1的，会是这个原因吗。其他的配置都和要求的一样，但是我已经调试这个错误两天了，还不能解决

**Comment by Henry1iu** [comment]
Hi, 

你有检查过你生成的数据么? 麻烦描述一下你的"train_intermediate"文件夹中的数据内容. 另外torch_geometric的相应library是否和我的一致?

Best,
Jianbang

**Comment by vnben** [comment]
在train_intermediate里面有processed和raw两个文件夹，processed里面有三个文件，data.pt,pre_filter.pt和pre_transform.pt.raw里面是一些features的数据。按照预处理之前的要求进行了配置，torch_geometric里面的几个下载了对应的库，除了python我用的是3.8.10，其他是一致的。另外cuda使用的是11.1版本，我翻往期回答看见了你用的是10.2，我就又创造了一个cuda10.2和py3.8的环境。但是在这个里面pip install torch_geometric的时候一直是成功的，但是不能import进去，其他几个库换成对应的cuda版本也是pip成功。上网搜索的时候说是cuda版本的问题所以不能import。我又换回了cuda11.1，变回了原先的错误&nbsp;


张婉婷
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LIU ***@***.***&gt;; 
发送时间: 2022年5月30日(星期一) 晚上6:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Henry1iu/TNT-Trajectory-Predition]  RuntimeError: [enforce fail at inline_container.cc:222] . file not found: archive/data/94577727233808 (Issue #20)





 
Hi,
 
你有检查过你生成的数据么? 麻烦描述一下你的"train_intermediate"文件夹中的数据内容. 另外torch_geometric的相应library是否和我的一致?
 
Best,
 Jianbang

**Comment by Henry1iu** [comment]
Hi, 

请问你的安装过程是否按照[官方的流程](https://pytorch-geometric.readthedocs.io/en/1.7.2/notes/installation.html)?
因为我使用的是1.7.2的版本, 所以安装过程比较复杂, 要确保torch_geometric的dependency版本正确. 

Best,
Jianbang

**Comment by Henry1iu** [comment]
Hi,

你可以先尝试先生成一个small subset, 详情可以看script/preprocessing.bash. 先用small subset会方便一点.

Best,
Jianbang

**Comment by vnben** [comment]
Torch_geometric底下的四个库是下载对应的安装包，然后pip install&nbsp; &nbsp;.whl下载的。随后的torch_geometric是直接pip install torch_geometric==1.7.2，直接下载的。上面显示按照成功后就没有在意了。
那可能是我的下载方式的问题



---Original---
From: "LIU ***@***.***&gt;
Date: Mon, May 30, 2022 18:31 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Henry1iu/TNT-Trajectory-Predition]  RuntimeError: [enforce failat inline_container.cc:222] . file not found: archive/data/94577727233808(Issue #20)




 
Hi,
 
请问你的安装过程是否按照官方的流程?
 因为我使用的是1.7.2的版本, 所以安装过程比较复杂, 要确保torch_geometric的dependency版本正确.
 
Best,
 Jianbang

**Comment by vnben** [comment]
好的！谢谢
&nbsp;


张婉婷
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LIU ***@***.***&gt;; 
发送时间: 2022年5月30日(星期一) 晚上6:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Henry1iu/TNT-Trajectory-Predition]  RuntimeError: [enforce fail at inline_container.cc:222] . file not found: archive/data/94577727233808 (Issue #20)





 
Hi,
 
你可以先尝试先生成一个small subset, 详情可以看script/preprocessing.bash. 先用small subset会方便一点.
 
Best,
 Jianbang

**Comment by Henry1iu** [comment]
Hi,

请问dataloading的部分解决了么？我这边测试过cuda11.1，没有产生类似的bug。应该是torch_geometric的dependecy版本不对的问题。

如果已经顺利解决，我将关闭这个issue。

Best,
Jianbang

**Comment by Dongyangxdu** [comment]
我也遇到了相同的问题，请问您解决了吗？
