### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:  /argoverse-api-master/map_files/pruned_argoverse_PIT_10314_vector_map.xml'

### ISSUE THREAD

**Issue by Yuaneen** [Henry1iu/TNT-Trajectory-Predition#7]
I install all dependencies according to your requirements,and run ./script/preprocessing.bash,but get an error:

(TNT-Trajectory-Predition) wenyuan@wenyuan-Precision-7920-Tower:~/PycharmProjects/TNT-Trajectory-Predition-main$ ./scripts/preprocessing.bash 
Traceback (most recent call last):
  File "core/util/preprocessor/argoverse_preprocess_v2.py", line 423, in <module>
    argoverse_processor = ArgoversePreprocessor(root_dir=raw_dir, split=split, save_dir=interm_dir)
  File "core/util/preprocessor/argoverse_preprocess_v2.py", line 49, in __init__
    self.am = ArgoverseMap()
  File "/home/wenyuan/tools/argoverse-api-master/argoverse/map_representation/map_api.py", line 66, in __init__
    self.city_lane_centerlines_dict = self.build_centerline_index()
  File "/home/wenyuan/tools/argoverse-api-master/argoverse/map_representation/map_api.py", line 172, in build_centerline_index
    city_lane_centerlines_dict[city_name] = load_lane_segments_from_xml(xml_fpath)
  File "/home/wenyuan/tools/argoverse-api-master/argoverse/data_loading/vector_map_loader.py", line 310, in load_lane_segments_from_xml
    tree = ET.parse(os.fspath(map_fpath))
  File "/home/wenyuan/anaconda3/envs/TNT-Trajectory-Predition/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "/home/wenyuan/anaconda3/envs/TNT-Trajectory-Predition/lib/python3.7/xml/etree/ElementTree.py", line 587, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/wenyuan/tools/argoverse-api-master/map_files/pruned_argoverse_PIT_10314_vector_map.xml'

is there some problem with package "argoverse 1.1.0"?  hope to reply, thanks.

**Comment by Henry1iu** [comment]
Hi Yuaneen,

It seems you didn't download the map data. Please follow the installation instruction provided on their official repository. 

Regards,
Jianbang
